# Generated by Django 3.2.7 on 2021-10-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='lang'),
        ),
    ]
