# Generated by Django 3.2.7 on 2021-11-10 11:15

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211110_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', '$'), ('EUR', '€'), ('₽', '₽')], default='₽', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='₽', max_digits=8),
        ),
    ]
