# Generated by Django 3.2.7 on 2021-10-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'FORMING'), ('STP', 'SENT TO PROCESS'), ('PD', 'PAID'), ('PRD', 'IN PROCESS'), ('RDY', 'READY'), ('CNL', 'CANCELLED')], default='FM', max_length=3, verbose_name='status'),
        ),
    ]
